hmcts/fpl-ccd-data-migration-tool

build.gradle
**Before creating a pull request make sure that:**
Gradle ccd-case-migration version updated to 3.0.0
```
[ ] Yes
[x] No
```
=> ccd-case-migration updated to 3.0.0

README.md
Add additional info to the README to inform of how the migration works internally
=> chore: add migration info

src/main/resources/application.properties
**Before creating a pull request make sure that:**
Please remove this line and everything above and fill the following sections:
https://tools.hmcts.net/jira/browse/DFPL-841
Remove password from application.properties
```
[ ] Yes
[ ] No
```
=> Dfpl 841: Fortify - migration tool remove password

src/main/java/uk/gov/hmcts/reform/migration/CaseMigrationProcessor.java, src/main/java/uk/gov/hmcts/reform/migration/service/DataMigrationServiceImpl.java
https://tools.hmcts.net/jira/browse/DFPL-1233
improved stats logs
```
[ ] Yes
[x ] No
```
=> DFPL:1233: improved stats logs

build.gradle, config/owasp/suppressions.xml, src/main/java/uk/gov/hmcts/reform/domain/model/DfjAreaCourtMapping.java, src/main/java/uk/gov/hmcts/reform/domain/util/ResourceReader.java, src/main/java/uk/gov/hmcts/reform/migration/CaseMigrationProcessor.java, src/main/java/uk/gov/hmcts/reform/migration/ccd/CoreCaseDataService.java, src/main/java/uk/gov/hmcts/reform/migration/query/ElasticSearchQuery.java, src/main/java/uk/gov/hmcts/reform/migration/repository/ElasticSearchRepository.java, src/main/java/uk/gov/hmcts/reform/migration/service/DataMigrationServiceImpl.java, src/main/java/uk/gov/hmcts/reform/migration/service/DfjAreaLookUpService.java, src/main/resources/static_data/dfjAreaCourtMapping.json, src/test/java/uk/gov/hmcts/reform/fpl/utils/ResourceReaderTest.java, src/test/java/uk/gov/hmcts/reform/migration/CaseMigrationProcessorTest.java, src/test/java/uk/gov/hmcts/reform/migration/ccd/CoreCaseDataServiceTest.java, src/test/java/uk/gov/hmcts/reform/migration/service/DataMigrationServiceImplTest.java, src/test/java/uk/gov/hmcts/reform/query/ElasticSearchQueryTest.java, src/test/java/uk/gov/hmcts/reform/repository/ElasticSearchRepositoryTest.java
**Before creating a pull request make sure that:**
Please remove this line and everything above and fill the following sections:
https://tools.hmcts.net/jira/browse/DFPL-1240
dfj area migration
```
[ ] Yes
[ ] No
```
=> Dfpl 1240: dfj area migration

build.gradle, charts/fpl-cron-ccd-data-migration-tool/Chart.yaml, config/owasp/suppressions.xml, src/main/java/uk/gov/hmcts/reform/migration/CaseMigrationProcessor.java
https://tools.hmcts.net/jira/browse/DFPL-1240
Improved stats logs, gradle and suppression
```
[ ] Yes
[ x] No
```
=> DFPL-1240: Improved stats logs, gradle and suppression

src/main/java/uk/gov/hmcts/reform/migration/service/DataMigrationServiceImpl.java, src/main/resources/static_data/dfjAreaCourtMapping.json
DFPL-1124
- Update Brighton code to 554 not 150!
```
[ ] Yes
[X ] No
```
=> DFPL-1124: Update the query to ignore those already migrated + update mapping

config/owasp/suppressions.xml, src/main/java/uk/gov/hmcts/reform/migration/service/DataMigrationServiceImpl.java
https://tools.hmcts.net/jira/browse/DFPL-1352
- Add basic migration using callback only to tool
```
[ ] Yes
[X] No
```
=> DFPL-1352: Add sendToCtsc migration to tool

src/main/java/uk/gov/hmcts/reform/migration/service/DataMigrationServiceImpl.java
https://tools.hmcts.net/jira/browse/DFPL-1663
https://tools.hmcts.net/jira/browse/DFPL-1701
Add migration functions for DFPL-1663 and DFPL-1701
```
[ ] Yes
[X] No
```
=> DFPL-1663: Add migration function

config/owasp/suppressions.xml, src/main/java/uk/gov/hmcts/reform/migration/service/DataMigrationServiceImpl.java
https://tools.hmcts.net/jira/browse/DFPL-1561
- Add AM role migration ID + queries
```
[ ] Yes
[X] No
```
=> DFPL-1561: Create AM roles for Judiciary + Legal Advisers migration

src/main/java/uk/gov/hmcts/reform/migration/service/DataMigrationServiceImpl.java
https://tools.hmcts.net/jira/browse/DFPL-1722
https://tools.hmcts.net/jira/browse/DFPL-1724
https://tools.hmcts.net/jira/browse/DFPL-1725
Add migration functions for DFPL-1722, DFPL-1724 and DFPL-1725
```
[ ] Yes
[X] No
```
=> DFPL-1722: Add migration functions

src/main/java/uk/gov/hmcts/reform/migration/service/DataMigrationServiceImpl.java
https://tools.hmcts.net/jira/browse/DFPL-1734
https://tools.hmcts.net/jira/browse/DFPL-1739
Add migration functions for DFPL-1734 and DFPL-1739
```
[ ] Yes
[X] No
```
=> DFPL-1734: Add migration functions

src/main/java/uk/gov/hmcts/reform/JudicialUserRequest.java, src/main/java/uk/gov/hmcts/reform/migration/CaseMigrationRunner.java, src/main/java/uk/gov/hmcts/reform/migration/JudicialUserProfile.java, src/main/java/uk/gov/hmcts/reform/migration/repository/JudicialApi.java, src/main/resources/application.properties
DFPL-1561
- Log judges in demo for testing api endpoint
```
[ ] Yes
[X] No
```
=> Dfpl 1561 judge migration testing

.github/renovate.json
Following guide here https://hmcts.github.io/cloud-native-platform/guides/automated-dependency-updates.html#automated-dependency-updates
```
[ ] Yes
[ x] No
```
=> Enable renovate in migration tool repo

src/main/java/uk/gov/hmcts/reform/migration/service/DataMigrationServiceImpl.java
https://tools.hmcts.net/jira/browse/DFPL-1702
Set case state to be CASE_MANAGEMENT
=> DFPL-1702 INC5539294 Unable to reopen case - manage cases

src/main/java/uk/gov/hmcts/reform/migration/service/DataMigrationServiceImpl.java
https://tools.hmcts.net/jira/browse/DFPL-1773
DFPL-1773 update migration tools mapping
=> DFPL-1773 update migration tools mapping

src/main/java/uk/gov/hmcts/reform/migration/service/DataMigrationServiceImpl.java
https://tools.hmcts.net/jira/browse/DFPL-1748
Add migration function for DFPL-1748
=> DFPL-1748: Add migration function

CODEOWNERS, build.gradle
=> Rollback renovate prs

src/main/java/uk/gov/hmcts/reform/migration/service/DataMigrationServiceImpl.java
https://tools.hmcts.net/jira/browse/DFPL-1769
- Update ES query for tonights migration
=> DFPL-1769: Update query to only migrate submitted + onwards cases in progress

src/main/java/uk/gov/hmcts/reform/migration/service/DataMigrationServiceImpl.java
https://tools.hmcts.net/jira/browse/DFPL-1774
DFPL-1774 update migration tools
=> DFPL-1774 update migration tools

src/main/java/uk/gov/hmcts/reform/migration/service/DataMigrationServiceImpl.java
https://tools.hmcts.net/jira/browse/DFPL-1793
1. Migration script DFPL-1793
=> DFPL-1793 INC5552381 solicitor unable to action NOC function

src/main/java/uk/gov/hmcts/reform/migration/service/DataMigrationServiceImpl.java
https://tools.hmcts.net/jira/browse/DFPL-1802
Setting up migration tool for DFPL-1802
=> DFPL-1802 INC5536958 Bedford LA added as Applicant and Respondent

src/main/java/uk/gov/hmcts/reform/migration/service/DataMigrationServiceImpl.java
https://tools.hmcts.net/jira/browse/DFPL-1810
DFPL-1810 INC5554170 - Document needs removing from wrong case
=> DFPL-1810 INC5554170 - Document needs removing from wrong case

src/main/java/uk/gov/hmcts/reform/migration/service/DataMigrationServiceImpl.java
https://tools.hmcts.net/jira/browse/DFPL-1813
INC5552093 - NOC not working
=> DFPL-1813: INC5552093 - NOC not working

src/main/java/uk/gov/hmcts/reform/migration/service/DataMigrationServiceImpl.java
https://tools.hmcts.net/jira/browse/DFPL-1837
Changes for this migration
=> triggerOnlyMigration for DFPL-1837

src/main/java/uk/gov/hmcts/reform/migration/service/DataMigrationServiceImpl.java
https://tools.hmcts.net/jira/browse/DFPL-1842
=> DFPL-1842: Remove Position Statement Child

src/main/java/uk/gov/hmcts/reform/migration/service/DataMigrationServiceImpl.java
https://tools.hmcts.net/jira/browse/DFPL-1850
=> DFPL-1850:NOC Data Migration

src/main/java/uk/gov/hmcts/reform/migration/service/DataMigrationServiceImpl.java
https://tools.hmcts.net/jira/browse/DFPL-1883
remove position statement
=> DFPL-1883 update migration tool

src/main/java/uk/gov/hmcts/reform/migration/service/DataMigrationServiceImpl.java
https://tools.hmcts.net/jira/browse/DFPL-1887
update migration tools
=> DFPL-1887 update migration tools

charts/fpl-cron-ccd-data-migration-tool/Chart.yaml, src/main/java/uk/gov/hmcts/reform/migration/service/DataMigrationServiceImpl.java
https://tools.hmcts.net/jira/browse/DFPL-1899
Remove names from grounds
=> DFPL-1899: Removal of names from grounds

src/main/java/uk/gov/hmcts/reform/migration/service/DataMigrationServiceImpl.java
https://tools.hmcts.net/jira/browse/DFPL-1926
INC5567120 A Judicial messages needs to be removed due to a data issue -NE23C50645
=> DFPL-1926 update migration tools

src/main/java/uk/gov/hmcts/reform/migration/service/DataMigrationServiceImpl.java, src/test/java/uk/gov/hmcts/reform/migration/service/DataMigrationServiceImplTest.java
https://tools.hmcts.net/jira/browse/DFPL-1921
Add migration for DFPL-1921
=> DFPL-1921 INC5566351 Document removal on LS23C50636

build.gradle
=> Fix CVE-2023-6378

build.gradle, src/main/java/uk/gov/hmcts/reform/migration/service/DataMigrationServiceImpl.java
https://tools.hmcts.net/jira/browse/DFPL-1902
=> DFPL-1902 Data Migration for FurtherEvidenceDocument without Document Type

config/owasp/suppressions.xml, src/main/java/uk/gov/hmcts/reform/migration/service/DataMigrationServiceImpl.java
https://tools.hmcts.net/jira/browse/DFPL-1855
Middlesborough court epimmsID typo + Migration
=> DFPL-1855 Middlesborough court epimmsID typo + Migration

src/main/java/uk/gov/hmcts/reform/migration/service/DataMigrationServiceImpl.java
[DFPL-1934](https://tools.hmcts.net/jira/browse/DFPL-1934)
- Logging migration if needed to reindex
- ES query for all non-deleted/open state cases to run the NoC clearing one
=> DFPL-1934: Add migration function which skips if no field to clear

src/main/java/uk/gov/hmcts/reform/migration/service/DataMigrationServiceImpl.java
https://tools.hmcts.net/jira/browse/DFPL-1954
https://tools.hmcts.net/jira/browse/DFPL-1948
Add migration functions to mapping for DFPl-1954 and DFPL-1948
=> DFPL-1954: Add migration functions to mapping

src/main/java/uk/gov/hmcts/reform/migration/service/DataMigrationServiceImpl.java
https://tools.hmcts.net/jira/browse/DFPL-2002
=> DFPL-2002 INC5574764 Document needs to be removed

src/main/java/uk/gov/hmcts/reform/migration/service/DataMigrationServiceImpl.java
https://tools.hmcts.net/jira/browse/DFPL-1957
https://tools.hmcts.net/jira/browse/DFPL-1993
Migration on position statement (child/respondent)
=> DFPL-1957/DFPL-1993 Migration script to remove position statements.

src/main/java/uk/gov/hmcts/reform/migration/service/DataMigrationServiceImpl.java
https://tools.hmcts.net/jira/browse/DFPL-2013
https://tools.hmcts.net/jira/browse/DFPL-1964
Add migration functions to map
=> DFPL-2013: Add migration functions to map

charts/fpl-cron-ccd-data-migration-tool/Chart.yaml
Upgrade job chart version to 2.1.0
=> Upgrade chart version to 2.1.0

src/main/java/uk/gov/hmcts/reform/migration/service/DataMigrationServiceImpl.java
https://tools.hmcts.net/jira/browse/DFPL-1947
https://tools.hmcts.net/jira/browse/DFPL-1959
Add migration functions to map
=> DFPL-1947: Add migration functions to map

src/main/java/uk/gov/hmcts/reform/migration/service/DataMigrationServiceImpl.java
https://tools.hmcts.net/jira/browse/DFPL-2033
Add migration ID to mapping
=> DFPL-2033: Add migration ID to mapping

charts/fpl-cron-ccd-data-migration-tool/Chart.yaml
Upgrade deprecated version of job helm
=> Upgrading job helm chart

src/main/java/uk/gov/hmcts/reform/migration/service/DataMigrationServiceImpl.java
https://tools.hmcts.net/jira/browse/DFPL-2094
INC5568344 Closure dates not being backdated - Migration of past cases
=> Dfpl 2094 update migration tools

src/main/java/uk/gov/hmcts/reform/migration/service/DataMigrationServiceImpl.java
https://tools.hmcts.net/jira/browse/DFPL-1956
- Add migration run script
=> DFPL-1956: Add script for running migration

src/main/java/uk/gov/hmcts/reform/migration/service/DataMigrationServiceImpl.java
https://tools.hmcts.net/jira/browse/DFPL-1233
Adding ES query and run functions for hearing types migration.
=> Dfpl 1233 - Migration for hearing types

src/main/java/uk/gov/hmcts/reform/migration/service/DataMigrationServiceImpl.java
https://tools.hmcts.net/jira/browse/DFPL-2118
Remove judicial message
=> DFPL-2118: Remove judicial message

src/main/java/uk/gov/hmcts/reform/migration/service/DataMigrationServiceImpl.java
https://tools.hmcts.net/jira/browse/DFPL-2177
Add migration for the removal of urgent directions order
=> DFPL-2177: Removal of urgent directions order

src/main/java/uk/gov/hmcts/reform/migration/service/DataMigrationServiceImpl.java
https://tools.hmcts.net/jira/browse/DFPL-1882
Cleanup "Unknown" title allocated judges
=> Cleanup Unknown title allocated judges

src/main/java/uk/gov/hmcts/reform/migration/service/DataMigrationServiceImpl.java
https://tools.hmcts.net/jira/browse/DFPL-2051
=> DFPL-2051: Add migration functions to map

src/main/java/uk/gov/hmcts/reform/migration/service/DataMigrationServiceImpl.java
DFPL-1978
- Setup migration tool for two migrations
=> DFPL-1978: Setup migration tool

src/main/java/uk/gov/hmcts/reform/migration/service/DataMigrationServiceImpl.java
=> DFPL-2205: migration setup

src/main/java/uk/gov/hmcts/reform/migration/service/DataMigrationServiceImpl.java
DFPL-1918
- readd the migration functions
- [NO] Does this PR introduce a breaking change
=> DFPL-1918: Roles migration

src/main/java/uk/gov/hmcts/reform/migration/service/DataMigrationServiceImpl.java
https://tools.hmcts.net/jira/browse/DFPL-1233
Update the migration tool to check for cases where cancelldHearingDetails has a hearing type OTHER. Need this for any cases where there is only a cancelled hearing of type OTHER.
=> Updating migration to check cancelled hearing details OTHER

src/main/java/uk/gov/hmcts/reform/migration/service/DataMigrationServiceImpl.java
DFPL-2284
- Add migration function
=> DFPL-2284: Add migration function

src/main/java/uk/gov/hmcts/reform/migration/service/DataMigrationServiceImpl.java
https://tools.hmcts.net/jira/browse/DFPL-2296
DFPL-2296 update migration tools
=> DFPL-2296 update migration tools

src/main/java/uk/gov/hmcts/reform/migration/service/DataMigrationServiceImpl.java
https://tools.hmcts.net/jira/browse/DFPL-2311
DFPL-2311 update migration tools
=> DFPL-2311 update migration tools

src/main/java/uk/gov/hmcts/reform/migration/service/DataMigrationServiceImpl.java
https://tools.hmcts.net/jira/browse/DFPL-2299
DFPL-2299 Migration remove urgent direction order
=> DFPL-2299 Update migration tools

src/main/java/uk/gov/hmcts/reform/migration/service/DataMigrationServiceImpl.java
https://tools.hmcts.net/jira/browse/DFPL-2339
Update for Kent outsourcing policy migration
=> DFPL-2339: Migrate outsourcing policy for Kent

src/main/java/uk/gov/hmcts/reform/migration/service/DataMigrationServiceImpl.java
https://tools.hmcts.net/jira/browse/DFPL-2331
Add migration for removal of child names
=> DFPL-2331: Remove child names from proceedings

src/main/java/uk/gov/hmcts/reform/migration/service/DataMigrationServiceImpl.java, src/test/java/uk/gov/hmcts/reform/migration/CaseMigrationProcessorTest.java
[DFPL-2323](https://tools.hmcts.net/jira/browse/DFPL-2323)
Remove manage orders temp field questions
=> DFPL-2323: Migration to remove temp field

src/main/java/uk/gov/hmcts/reform/migration/service/DataMigrationServiceImpl.java
DFPL-2354
- Setup migration tool to remove UDO
=> DFPL-2354: Setup migration function

src/main/java/uk/gov/hmcts/reform/migration/service/DataMigrationServiceImpl.java
https://tools.hmcts.net/jira/browse/DFPL-2474
Migration to remove PVP document on case
=> Add migration for DFPL-2474

src/main/java/uk/gov/hmcts/reform/migration/service/DataMigrationServiceImpl.java
https://tools.hmcts.net/jira/browse/DFPL-2417
Data migration to remove respondentsAwareReason
=> [DFPL-2417] Data migration to remove respondentsAwareReason

src/main/java/uk/gov/hmcts/reform/migration/service/DataMigrationServiceImpl.java
Add migration to remove invalid characters from telephone number on respondent
https://tools.hmcts.net/jira/browse/DFPL-2356
=> DFPL-2356: Add migration to remove telephone number

src/main/java/uk/gov/hmcts/reform/migration/service/DataMigrationServiceImpl.java
https://tools.hmcts.net/jira/browse/DFPL-2492
Migration removing text from thresholdDetails
```
[ ] Yes
[X] No
```
=> [DFPL-2492] Migration to remove text from thresholdDetails

src/main/java/uk/gov/hmcts/reform/migration/service/DataMigrationServiceImpl.java
See [DFPL-2491](https://tools.hmcts.net/jira/browse/DFPL-2491)
- Setup migration function
=> DFPL-2491: Setup migration function

src/main/java/uk/gov/hmcts/reform/migration/service/DataMigrationServiceImpl.java
https://tools.hmcts.net/jira/browse/DFPL-2551
Update migration tools
=> DFPL-2551 Update migration tools

src/main/java/uk/gov/hmcts/reform/migration/service/DataMigrationServiceImpl.java
https://tools.hmcts.net/jira/browse/DFPL-2507
Update migrations map
=> DFPL-2507: Update migrations map

src/main/java/uk/gov/hmcts/reform/migration/service/DataMigrationServiceImpl.java
https://tools.hmcts.net/jira/browse/DFPL-2580
Setup migration
=> DFPL-2580: Setup migration function

src/main/java/uk/gov/hmcts/reform/migration/service/DataMigrationServiceImpl.java
https://tools.hmcts.net/jira/browse/DFPL-2579
=> DFPL-2579: Setup migration function

src/main/java/uk/gov/hmcts/reform/migration/service/DataMigrationServiceImpl.java, src/test/java/uk/gov/hmcts/reform/migration/service/DataMigrationServiceImplTest.java
[DFPL-2585](https://tools.hmcts.net/jira/browse/DFPL-2585)
- Setup CLOSED case query for the role cleanup migration
- Confirmed working in AAT environment, see ticket comments
=> DFPL-2585: Setup migration, cleanup old queries

src/main/java/uk/gov/hmcts/reform/migration/service/DataMigrationServiceImpl.java
https://tools.hmcts.net/jira/browse/DFPL-2597
Migration to remove statement of service
=> DFPL-2597: Remove statement of service migration

src/main/java/uk/gov/hmcts/reform/migration/service/DataMigrationServiceImpl.java
https://tools.hmcts.net/jira/browse/DFPL-2605
Adding migration to update outsourcing policy.
Tested migration on a case locally and verified output.
- [ x] commit messages are meaningful and follow good commit message guidelines
- [x ] README and other documentation has been updated / added (if needed)
- [ x] tests have been updated / new tests has been added (if needed)
- [x ] Does this PR introduce a breaking change
=> DFPL-2605: Add migration to update outsourcing policy.

src/main/java/uk/gov/hmcts/reform/migration/service/DataMigrationServiceImpl.java
https://tools.hmcts.net/jira/browse/DFPL-2610
Remove strings from legal basis details
=> DFPl-2610: Remove legal basis information

src/main/java/uk/gov/hmcts/reform/migration/service/DataMigrationServiceImpl.java
https://tools.hmcts.net/jira/browse/DFPL-2613
Adds migration to remove text from legal basis tab for case.
Tested on case locally.
- [x ] commit messages are meaningful and follow good commit message guidelines
- [x ] README and other documentation has been updated / added (if needed)
- [x ] tests have been updated / new tests has been added (if needed)
- [ x] Does this PR introduce a breaking change
=> DFPL-2613 Add migration to remove text from legal basis for case.

src/main/java/uk/gov/hmcts/reform/migration/service/DataMigrationServiceImpl.java
https://tools.hmcts.net/jira/browse/DFPL-2619
Updating migration tool
- [ x] commit messages are meaningful and follow good commit message guidelines
- [ x] README and other documentation has been updated / added (if needed)
- [ x] tests have been updated / new tests has been added (if needed)
- [ x] Does this PR introduce a breaking change
=> DFPL-2619 Add migration to update third party applicant.

src/main/java/uk/gov/hmcts/reform/migration/service/DataMigrationServiceImpl.java
https://tools.hmcts.net/jira/browse/DFPL-2621
Add migration for outsourcing policy update
=> DFPL-2621: Update outsourcing org policy to itn

src/main/java/uk/gov/hmcts/reform/migration/service/DataMigrationServiceImpl.java
https://tools.hmcts.net/jira/browse/DFPL-2635
https://tools.hmcts.net/jira/browse/DFPL-2636
Add both migrations to migrations map
=> DFPL-2635: Add both migrations to migrations map

src/main/java/uk/gov/hmcts/reform/migration/service/DataMigrationServiceImpl.java
https://tools.hmcts.net/jira/browse/DFPL-2642
3rd party policy to be set to Pathfinder legal
=> DFPL-2642: 3rd Party policy migration

src/main/java/uk/gov/hmcts/reform/migration/service/DataMigrationServiceImpl.java
https://tools.hmcts.net/jira/browse/DFPL-2638
Adding migration to update third party applicant
=> Add migration to update third party applicant.

src/main/java/uk/gov/hmcts/reform/migration/service/DataMigrationServiceImpl.java
https://tools.hmcts.net/jira/browse/DFPL-2640
Updating migration tool for third party applicant migration
=> DFPL-2640: Update migration tool for third party solicitor migration

src/main/java/uk/gov/hmcts/reform/migration/service/DataMigrationServiceImpl.java
https://tools.hmcts.net/jira/browse/DFPL-2487
- Setup tool for OOH migration
- 
- [no] Does this PR introduce a breaking change
=> DFPL-2487: Setup migration for role assignment rebuild

build.gradle, gradle/wrapper/gradle-wrapper.properties
See [PROJ-XXXXXX](https://tools.hmcts.net/jira/browse/PROJ-XXXXXX)
=> Revert renovate

src/main/java/uk/gov/hmcts/reform/migration/service/DataMigrationServiceImpl.java
[DFPL-2713](https://tools.hmcts.net/jira/browse/DFPL-2713)
- Setup migration function
- tested against case locally
=> DFPL-2713: Setup migration for redaction

src/main/java/uk/gov/hmcts/reform/migration/service/DataMigrationServiceImpl.java
https://tools.hmcts.net/jira/browse/DFPL-2739
Add reference to migration in migration tool.
Tested migration locally against case.
=> DFPL-2739: Add migration to remove draft order from additional application

src/main/java/uk/gov/hmcts/reform/migration/service/DataMigrationServiceImpl.java
https://tools.hmcts.net/jira/browse/DFPL-2733
Add migration to mapping
=> DFPL-2733: Add migration to mapping

src/main/java/uk/gov/hmcts/reform/migration/service/DataMigrationServiceImpl.java
DFPL-2360
- Add ES Query to migrate all (non-deleted) cases, as needing to add a single metadata field to all (to make show conditions work, metadata field will be filled in going forwards on ALL cases)
=> DFPL-2360: Setup ES Query for all (non-deleted) cases for OOH migration

build.gradle, src/main/java/uk/gov/hmcts/reform/migration/service/DataMigrationServiceImpl.java
https://tools.hmcts.net/jira/browse/DFPL-2423
Query all case with "proceeding" field
=> DFPL-2423 Migration tools

src/main/java/uk/gov/hmcts/reform/migration/service/DataMigrationServiceImpl.java
See [PROJ-XXXXXX](https://tools.hmcts.net/jira/browse/PROJ-XXXXXX)
=> DFPL-2756: Add migration to service

src/main/java/uk/gov/hmcts/reform/migration/service/DataMigrationServiceImpl.java
See [PROJ-XXXXXX](https://tools.hmcts.net/jira/browse/PROJ-XXXXXX)
=> DFPL-2360: Add migration function

Dockerfile, build.gradle, charts/fpl-cron-ccd-data-migration-tool/Chart.yaml, charts/fpl-cron-ccd-data-migration-tool/values.yaml, gradle/wrapper/gradle-wrapper.properties, lib/applicationinsights.json, src/main/java/uk/gov/hmcts/reform/fpl/model/common/Element.java, src/main/java/uk/gov/hmcts/reform/migration/CaseMigrationRunner.java, src/main/java/uk/gov/hmcts/reform/migration/service/DataMigrationServiceImpl.java
See [DFPL-2742](https://tools.hmcts.net/jira/browse/DFPL-2742)
- Bump spring boot to 3.4.5
- Bump spring security
- Adds appinsights configuration from #283 
- Run locally
- TODO: Run in demo
=> DFPL-2742: Upgrade spring, clean up deps

src/main/java/uk/gov/hmcts/reform/migration/service/DataMigrationServiceImpl.java
See [PROJ-XXXXXX](https://tools.hmcts.net/jira/browse/PROJ-XXXXXX)
Setting up DFPL-log migration to run over all non-deleted cases for testing performance of migration tool.
=> Update DFPL-log migration to run against all non-deleted cases.

src/main/java/uk/gov/hmcts/reform/migration/service/DataMigrationServiceImpl.java, src/main/resources/application.properties
https://tools.hmcts.net/jira/browse/DFPL-2797
Background
After a discussion with Jon, James on 27 Jun, Jon manage to reproduce the Logstash OOM error we encounter during the C110a migration by forcing Logstash to pick up large amount of large cases.
But, we want to reproduce this issue by using migration tools, help to closer simulate the issue we had in prod and try to dig out the limit.
Notes: Jon will update all the cases in perf test env, grouped by case data size. He will update the familyManCaseNumber to reflect the group, so that our migration tools can query cases base on the field.
Code changes:
Query all cases by the value of familyManCaseNumber field. Ideally to fetch the value from key vault or any other external configuration, so that we don't have to change the code every …
=> DFPL 2797 

config/owasp/suppressions.xml
Got a new CVE-2025-48976 on  commons-fileupload-1.5.jar where this dependecy is using by idam-java-client.
Suppress temporally until we find an IDAM update
=> Temp Suppress CVE-2025-48976

src/main/java/uk/gov/hmcts/reform/migration/CaseMigrationProcessor.java, src/main/java/uk/gov/hmcts/reform/migration/repository/ElasticSearchRepository.java, src/main/java/uk/gov/hmcts/reform/migration/service/DataMigrationServiceImpl.java, src/main/resources/application.properties
https://tools.hmcts.net/jira/browse/DFPL-2797
had a full run in perf test, but looks like got some issue with the ES query
Roll back for now, as we are not gonna to perform and more testing until next time (maybe next Wednesday)
=> Rollback DFPL-2797

src/main/java/uk/gov/hmcts/reform/migration/CaseMigrationProcessor.java, src/main/java/uk/gov/hmcts/reform/migration/query/EsQuery.java, src/main/java/uk/gov/hmcts/reform/migration/repository/ElasticSearchRepository.java, src/main/java/uk/gov/hmcts/reform/migration/service/DataMigrationServiceImpl.java
https://tools.hmcts.net/jira/browse/DFPL-2797
=> Rollback DFPL-2797 Revert "use search_after (#322)"

src/main/java/uk/gov/hmcts/reform/migration/service/DataMigrationServiceImpl.java
https://tools.hmcts.net/jira/browse/DFPL-2805
Add migration to remove seal cmo from case
=> DFPL-2805: Add migration to remove seal cmo

src/main/java/uk/gov/hmcts/reform/migration/service/DataMigrationServiceImpl.java
https://tools.hmcts.net/jira/browse/DFPL-2818
DFPL-2818 clear out deprecated HTML fields
=> DFPL-2818 clear out deprecated HTML fields
